name: test-system
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  run-linters:
      name: Run linters
      runs-on: ubuntu-latest

      steps:
        - name: Check out Git repository
          uses: actions/checkout@v4

        - name: Set up PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: "8.1"
            coverage: none
            tools: composer

        - name: Install PHP dependencies
          run: |
            composer install --prefer-dist --no-progress --no-ansi --no-interaction
            echo "${PWD}/vendor/bin" >> $GITHUB_PATH

        - name: Run linters
          uses: wearerequired/lint-action@v2
          with:
            php_codesniffer: true
        - run: composer update
        - run: make install
        - run: make test
        - run: make lint

        - name: Run test & publish code coverage
          uses: paambaati/codeclimate-action@v2.6.0
               # Add Code Climate secret key
          env:
             CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          with:
             coverageCommand: make test-coverage
             coverageLocations: ${{github.workplace}}/build/logs/clover.xml:clover
             debug: true